@startuml
title 주문 유스케이스 (장바구니 → 주문 생성)

actor "회원" as Member

rectangle "코드 마켓 시스템" {
'사용자 시나리오 (user_scenario.md 파일)의 기능별 시나리오 번호와 해당 다이어그램의 번호는 매핑되어 있습니다
  usecase "1.주문 화면 진입" as UC_Order
  usecase "2-1.상품 판매 가능 여부 재검증" as UC_RecheckSellable
  usecase "2-2.재고 재검증" as UC_RecheckStock
  usecase "3.주문 생성(CREATED)" as UC_CreateOrder
}

Member --> UC_Order

UC_Order --> UC_RecheckSellable : <<include>>
UC_Order --> UC_RecheckStock : <<include>>
UC_Order --> UC_CreateOrder : <<include>>

@enduml
