@startuml
title 마이페이지 - 내 주문 내역 조회 유스케이스

actor "회원" as Member

rectangle "코드 마켓 시스템" {
'사용자 시나리오 (user_scenario.md 파일)의 기능별 시나리오 번호와 해당 다이어그램의 번호는 매핑되어 있습니다
  usecase "2.내 주문 내역 조회" as UC_ViewOrders
  usecase "3.로그인 여부 검증" as UC_CheckLogin
  usecase "4.회원 주문 내역 목록 조회" as UC_FetchOrders

}

Member --> UC_ViewOrders

UC_ViewOrders --> UC_CheckLogin : <<include>>
UC_ViewOrders --> UC_FetchOrders : <<include>>

@enduml
