@startuml
title 주문 유스케이스 (장바구니 → 주문 생성)

actor "회원" as Member

rectangle "코드 마켓 시스템" {
'사용자 시나리오 (user_scenario.md 파일)의 기능별 시나리오 번호와 해당 다이어그램의 번호는 매핑되어 있습니다
  usecase "5-1-1.주문 화면 진입" as UC_Order
  usecase "5-1-2.주문 상품 정보 확인" as UC_RecheckProducts
  usecase "5-1-3.결제하기 진행" as UC_ProcessPayment
  usecase "5-1-7.주문 내용 확인" as UC_CheckOrderInfo
}

Member --> UC_Order
Member --> UC_ProcessPayment

UC_Order ..> UC_RecheckProducts : <<include>>
UC_ProcessPayment ..> UC_RecheckProducts : <<extend>>
UC_ProcessPayment ..> UC_CheckOrderInfo : <<include>>

@enduml
