@startuml
title 로그인 유스케이스

actor "회원" as Member

rectangle "코드 마켓 시스템" {
'사용자 시나리오 (user_scenario.md 파일)의 기능별 시나리오 번호와 해당 다이어그램의 번호는 매핑되어 있습니다
  usecase "2-1-1. 로그인 화면으로 진입" as UC_Login
  usecase "2-1-2. 이메일/비밀번호를 입력" as UC_WriteInformation
}

Member --> UC_Login

UC_Login ..> UC_WriteInformation : <<include>>

@enduml
