@startuml
title 상품 검색 유스케이스

actor "회원" as Member

rectangle "코드 마켓 시스템" {
'사용자 시나리오 (user_scenario.md 파일)의 기능별 시나리오 번호와 해당 다이어그램의 번호는 매핑되어 있습니다
  usecase "1.상품 검색" as UC_SearchProduct
  usecase "2.상품 목록 조회" as UC_ListProducts
  usecase "3.상품 상세 조회" as UC_ViewProductDetail
}

Member --> UC_SearchProduct
Member --> UC_ViewProductDetail

UC_SearchProduct --> UC_ListProducts : <<include>>
UC_ViewProductDetail --> UC_ListProducts : <<include>>
@enduml
