@startuml
title 회원가입 유스케이스

actor "회원" as Member

rectangle "코드 마켓 시스템" {
'사용자 시나리오 (user_scenario.md 파일)의 기능별 시나리오 번호와 해당 다이어그램의 번호는 매핑되어 있습니다
  usecase "1-1-1. 회원이 회원가입 화면으로 진입" as UC_Signup
  usecase "1-1-2. 회원이 이메일/비밀번호 입력" as UC_WriteInformation
}

Member --> UC_Signup

UC_Signup ..> UC_WriteInformation : <<include>>

@enduml
