@startuml
title 프로필 수정 유스케이스

actor "회원" as Member

rectangle "코드 마켓 시스템" {
'사용자 시나리오 (user_scenario.md 파일)의 기능별 시나리오 번호와 해당 다이어그램의 번호는 매핑되어 있습니다
  usecase "1.프로필 수정" as UC_EditProfile
  usecase "2.로그인 여부 검증" as UC_CheckLogin
  usecase "3.회원 상세 정보 조회" as UC_FetchMemberDetail
  usecase "4.수정 정보 검증" as UC_ValidateProfile
  usecase "5.회원 정보 수정 저장" as UC_SaveProfile

}

Member --> UC_EditProfile

UC_EditProfile --> UC_CheckLogin : <<include>>
UC_EditProfile --> UC_FetchMemberDetail : <<include>>
UC_EditProfile --> UC_ValidateProfile : <<include>>
UC_EditProfile --> UC_SaveProfile : <<include>>

@enduml
